### ISSUE TITLE
Errors while attempting to install Sparrow

### ISSUE THREAD

**Issue by spicy-Ferret** [tielqt/sparrow-for-mixer#5]
After approving the Mixer OAuth, localhost/dashboard refuses connection and an error, `Error: SQLITE_ERROR: no such table: users`, is printed in the commandline.

**Comment by evieveevee** [comment]
Just realized I should try and debug this; did you make the database by creating a new file at `/sqlite/mixer.db`?

**Comment by spicy-Ferret** [comment]
I did, yes.

**Comment by evieveevee** [comment]
Annnnnd now it's got a critical bug label for sure c:

**Comment by evieveevee** [comment]
@spicy-Ferret Can you pull the latest from master and see if you're still having this problem? You'll probably need to delete `sessions` and `sessions-journal` if they exist.

**Comment by spicy-Ferret** [comment]
I'm getting this when i try to setup the new master:
 `C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master>gulp sass --prod
[08:15:45] Using gulpfile ~\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\gulpfile.js
[08:15:45] Starting 'sass'...
[08:15:45] 'sass' errored after 5.53 ms
[08:15:45] TypeError: gulp.start is not a function
    at C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\gulpfile.js:37:8
    at taskWrapper (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)`

**Comment by evieveevee** [comment]
Latest master should now resolve this issue; unintended side effect of the 4.0 upgrade.

**Comment by spicy-Ferret** [comment]
Now I get this after OAauth, as well as connection refusal again:
`events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_ERROR: near "m": syntax error
Emitted 'error' event at:`

**Comment by evieveevee** [comment]
This error is incomplete. Please post the complete error.

**Comment by spicy-Ferret** [comment]
That had been the full output, but while trying to reproduce, I started getting the `no such table: users` error again before OAuth:
`C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\sqlite3\lib\trace.js:27
                    throw err;
                    ^

Error: SQLITE_ERROR: no such table: users
--> in Database#all('SELECT tokenDate from users WHERE id = 407355;', [], [Function])
    at Object.checkTokens (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\app\user.js:85:8)
    at Object.findById (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\app\user.js:53:28)
    at C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\index.js:61:8
    at pass (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport\lib\authenticator.js:357:9)
    at Authenticator.deserializeUser (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport\lib\authenticator.js:362:5)
    at SessionStrategy.authenticate (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport\lib\strategies\session.js:60:10)
    at attempt (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport\lib\middleware\authenticate.js:361:16)
    at authenticate (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport\lib\middleware\authenticate.js:362:7)
    at Layer.handle [as handle_request] (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\express\lib\router\layer.js:95:5)`

**Comment by spicy-Ferret** [comment]
that had been the full output, but whiile trying to reproduce, I got the `no such table: users` error again:

`C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\sqlite3\lib\trace.js:27
                    throw err;
                    ^

Error: SQLITE_ERROR: no such table: users
--> in Database#all('SELECT * from users WHERE id = 407355;', [], [Function])
    at Object.findById (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\app\user.js:62:8)
    at C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\index.js:61:8
    at pass (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport\lib\authenticator.js:357:9)
    at Authenticator.deserializeUser (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport\lib\authenticator.js:362:5)
    at SessionStrategy.authenticate (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport\lib\strategies\session.js:60:10)
    at attempt (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport\lib\middleware\authenticate.js:361:16)
    at authenticate (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport\lib\middleware\authenticate.js:362:7)
    at Layer.handle [as handle_request] (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\express\lib\router\index.js:317:13)`

**Comment by evieveevee** [comment]
That looks like you haven't wiped the sessions file. Make sure to wipe both
this, and mixer.db (to start it fresh).

I cannot duplicate the SQL error you're seeing.

**Comment by spicy-Ferret** [comment]
wiped those, got the last error back, heres the full log from `node index`:
`C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master>node index
express-session deprecated undefined resave option; provide resave option index.js:30:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option index.js:30:9
Express HTTP server listening on port 80
Express HTTPS server listening on port 443
GET /dashboard 200 717 - 235.039 ms
GET /css/dashboard.css 404 156 - 36.318 ms
Checking for the existence of the users table.
GET /auth/Mixer 302 84 - 21.064 ms
GET /auth/mixer/redirect 302 0 - 13.798 ms
DB closed after storing new tokens, back to you, passport!
Successful authentication, redirect to dash.
Connected to the SQlite database.
ROWS FOUND: 0
No user found. Creating user with ID 407355...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_ERROR: near "m": syntax error
Emitted 'error' event at:


C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master>`

**Comment by evieveevee** [comment]
I'm unable to duplicate this issue whatsoever; auth flow works perfectly fine over here on a fresh installation with the current Node LTS release (10.5.1). If there are any other steps you have to duplicate this issue, let me know. 

I've created a new branch (issue-5) with a possible fix based on what little information I can find, but would need you to test that branch and see if that resolves the issue here.

**Comment by spicy-Ferret** [comment]
I still got the same error, and haven't taken any steps outside your instructions other than carrying the same SSL cert and key between downloads of the program.

**Comment by evieveevee** [comment]
Alrighty, I eventually managed to run into this issue and found it was an issue with how I was formatting data for insertion. Should be okay now, please test from the latest `master`.

**Comment by spicy-Ferret** [comment]
Now I get this after OA: 

C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\sqlite3\lib\trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'replace' of undefined
    at Statement.db.all (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\app\user.js:22:38)
--> in Database#all('SELECT DISTINCT id name from users WHERE id = 407355;', [], [Function])
    at Object.findOrCreate (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\app\user.js:17:8)
    at Strategy._verify (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\index.js:49:10)
    at C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport-oauth2\lib\strategy.js:193:24
    at C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\passport-mixer\lib\passport-mixer\oauth2.js:66:7
    at passBackControl (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\oauth\lib\oauth2.js:134:9)
    at IncomingMessage.<anonymous> (C:\Users\victo\Downloads\sparrow-for-mixer-master\sparrow-for-mixer-master\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
